### ISSUE TITLE
Teensy 3.1 test code

### ISSUE THREAD

**Issue by pepijndevos** [mrjohnk/ADNS-9800#1]
Hey, I'm trying to make this work with the Teensy 3.1. No luck so far.

When I upload the sketch, I see this in the console. Nothing happens when I move the sensor.

```
Uploading firmware...
Optical Chip Initialized

---
Product_ID
0
110011
33

---
Inverse_Product_ID
3F
11001100
CC

---
SROM_Version
2A
10100100
A4

---
Motion
2
100000
20
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
```

These are the modifications I made.

Basically I changed the motion interrupt, because Teensy 3 allows interrupts on any pin.
I also slowed down the SPI for testing and because the ARM is faster than the AVR.
Then a bit of debugging.

``` diff
diff --git a/ADNS9800test.ino b/ADNS9800test.ino
index ddffcd2..7709f3e 100644
--- a/ADNS9800test.ino
+++ b/ADNS9800test.ino
@@ -50,7 +50,8 @@

 byte initComplete=0;

-const int ncs = 0;
+const int ncs = 8;
+const int mot = 9;

 extern const unsigned short firmware_length;
 extern prog_uchar firmware_data[];
@@ -60,13 +61,14 @@ void setup() {

   pinMode (ncs, OUTPUT);

-  attachInterrupt(0, UpdatePointer, FALLING);
+  attachInterrupt(mot, UpdatePointer, FALLING);

   SPI.begin();
   SPI.setDataMode(SPI_MODE3);
   SPI.setBitOrder(MSBFIRST);
-  SPI.setClockDivider(2);
+  SPI.setClockDivider(64);

+  delay(5000);
   performStartup();  
   dispRegisters();
   delay(100);
@@ -175,7 +177,7 @@ void UpdatePointer(void){
     readXY(&xydat[0]);
     Mouse.move(xydat[0],xydat[1]);
     }
-  //Serial.print("x");
+  Serial.print("x");
   }

 void dispRegisters(void){
```

Any idea what is wrong?
Thanks.

**Comment by brainchen98** [comment]
Hi,
I'm having trouble getting the t3.1 to work with the adns-9800.
Exactly what do you mean by
_I also needed to clear the motion register after setup and read all four of the registers in the interrupt._

**Comment by pepijndevos** [comment]
If there is data, you need to read it all to reset the MOT pin. So in setup I read all registers, and then when the MOT interrupt handles, I read all of them again.
https://github.com/pepijndevos/Dwergmuis/blob/master/dwergmuis.ino#L276-L280
https://github.com/pepijndevos/Dwergmuis/blob/master/dwergmuis.ino#L189-L207

**Comment by brainchen98** [comment]
I've tried a modified version of your code (removing the trackball specific things like Mouse.move()), however, it still doesn't work. The interrupt simply isn't called.

Also, I believe the device is working with SPI, as I get this output running the sketch that @mrjohnk supplies.
```
---
Product_ID
0
110011
33
---
Inverse_Product_ID
3F
11001100
CC
---
SROM_Version
2A
10100110
A6
---
Motion
2
0
0
```

**Comment by pepijndevos** [comment]
I don't know man... The SPI code seems to be working, so you could just poll the sensor.
Otherwise, put an oscilloscope on the MOT pin and debug that thing.

**Comment by brainchen98** [comment]
ok thanks.

**Comment by brainchen98** [comment]
I can poll the sensor, but I just get 0s.

**Comment by pepijndevos** [comment]
It's active low, so that means there is data. Now keep it very still and read all the registers, it should go high.

**Comment by brainchen98** [comment]
I understand the chip select pin (ncs) is active low. I'm not sure what you mean by read all the registers.

**Comment by brainchen98** [comment]
Also, when I get 0s, I'm actually polling the sensor manually (without relying on the interrupt).

**Comment by pepijndevos** [comment]
You mean poll the MOT line, or read out the data?
The MOT line is active low, so when `digitalRead(MOT)` returns 0, you should `adns_burst_motion(xy)`, and then it should go high.

If you are reading the data over SPI an *that* is 0, your chip is not properly initialised.`

**Comment by brainchen98** [comment]
Sorry. Miscommunication.
Ok. MOT is active low. It goes high when you read the registers, and then goes low again when the motion data is not read.

If I forcible call UpdatePointer(), then I will read 0, 0 from the x and y registers
From what I see, the MOT line is constantly low, and so the interrupt is never triggered. It seems like I'm not getting data.
