### ISSUE TITLE
Making a ADNS-9800 breakout board without the resistor circuit

### ISSUE THREAD

**Issue by arianen** [mrjohnk/ADNS-9800#4]
Hello there!

I am attempting to build a PCB with an intergrated ADNS-9800 and I have found your sketches to be a lovely starting point. I did however have a question about your V2.1 design: is the solder pad and resistor portion necessary to interface with the Teensy? I saw that a previous version of your .sch file didn't use them at all. I would only need to interface with the 3.3V from the Teensy, and don't need the 5V. Any help is appreciated!

**Comment by mrjohnk** [comment]
You are correct.   Since you are going to be using only 3.3v, you don't
need the resistors and solder pads.

**Comment by arianen** [comment]
Ok great, thanks for the quick reply!
