### ISSUE TITLE
I have a problem with ADDNS-9800

### ISSUE THREAD

**Issue by RC441** [mrjohnk/ADNS-9800#7]
Hey.

I'm experimenting with ADSN-9800.

For some reason, the coordinates received from the sensor do not move the cursor smoothly. If you move the sensor very slowly, the cursor moves with jerks and angularly.
If you move the sensor quickly, it is not so noticeable.

Is it possible to somehow increase the number of coordinates per second. I think that REG_Motion_Burst should help in this. Or am I wrong?

**Comment by mrjohnk** [comment]
The counts per inch is controlled with the Configuration_I register.  The
datasheet can supply information about this.

http://datasheet.octopart.com/ADNS-9800-Avago-datasheet-10666463.pdf
